# Sidebar navigation

- label: 'Welcome'
  link: '/'
- label: Music
  items:
    - label: 'My 150 (part 1)'
      link: '/music/my150'
    - label: 'My Wishlist'
      link: '/music/wishlist'
- label: Biking
  items:
    - label: 'Jump Bikes'
      link: '/mtb/jumps'
    - label: 'Skills'
      link: '/mtb/skills'
- label: Arma 3
  items:
    - label: 'Commentary'
      link: '/arma3/commentary'
    - label: 'Flight School'
      link: '/arma3/flightschool'
    - label: 'Killchain'
      link: '/arma3/killchain'
    - label: 'Voice Ops'
      link: '/arma3/voiceops'
    - label: 'Scripting'
      link: '/arma3/scripting'
- label: Helis
  items:
    - label: 'Heli Vids'
      link: '/helis/heliVids'
    - label: 'VN Heli Vids'
      link: '/helis/vn'
    - label: 'Film Clips'
      link: '/helis/filmFootage'
- label: Films
  items:
    - label: 'Reviews'
      link: '/films/reviews'
    - label: 'Shootouts'
      link: '/films/shoot'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
